version: '3.8'

services:
  # Minecraft server
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "1.20.1"
      MEMORY: "12G"                     # 12GB of RAM
      MOTD: "Type \"/help\" for help!"  # Message of the Day
      DIFFICULTY: "hard"                # peaceful, easy, normal, hard
      OPS: ""                           # Set this to your Minecraft username to be an operator
    ports:
      - "8080:8080"
      - "80:80"
      - "25565:25565"
      - "25566:25566"
    volumes:
      - ./mc-mods:/mods
      - ./mc-data:/data
    restart: unless-stopped

  restore-backup:
    image: itzg/mc-backup
    restart: "no"
    entrypoint: restore-tar-backup
    volumes:
      - ./mc-mods:/mods
      - ./mc-data:/data
      - ./mc-backups:/backups:ro

  backups:
    image: itzg/mc-backup
    depends_on:
      mc:
        condition: service_healthy
    environment:
      BACKUP_INTERVAL: "1h"
      RCON_HOST: mc
      INITIAL_DELAY: 0
    volumes:
      - ./mc-mods:/mods
      - ./mc-data:/data
      - ./mc-backups:/backups

volumes:
  mc-data: {}
