version: '3.8'

services:
  # Minecraft server
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      MOD_PLATFORM: "CURSEFORGE"
      CF_SERVER_MOD: "https://mediafilez.forgecdn.net/files/5339/476/All%20of%20Fabric%207-Server-2.2.2.zip"
      CF_OVERRIDES_EXCLUSIONS: |
        mods/iris*.jar
        mods/sodium*.jar
      MEMORY: "12G"                     # 12GB of RAM
      MOTD: "Type \"/help\" for help!"  # Message of the Day
      DIFFICULTY: "hard"                # peaceful, easy, normal, hard
      OPS: ""                           # Set this to your Minecraft username to be an operator
    ports:
      - "25565:25565"
    volumes:
      - ./mc-data:/data
    restart: unless-stopped

  # "init" container for mc to restore the data volume when empty  
  restore-backup:
    # Same image as mc, but any base image with bash and tar will work
    image: itzg/mc-backup
    restart: "no"
    entrypoint: restore-tar-backup
    volumes:
      # Must be same mount as mc service, needs to be writable
      - ./mc-data:/data
      # Must be same mount as backups service, but can be read-only
      - ./mc-backups:/backups:ro
  backups:
    image: itzg/mc-backup
    depends_on:
      mc:
        condition: service_healthy
    environment:
      BACKUP_INTERVAL: "1h"
      RCON_HOST: mc
      # since this service waits for mc to be healthy, no initial delay is needed
      INITIAL_DELAY: 0
    volumes:
      - ./mc-data:/data:ro
      - ./mc-backups:/backups

volumes:
  mc-data: {}
